language: python
matrix:
  include:
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
  - os: linux
    python: 3.7
    dist: xenial
    sudo: true
  - os: osx
    env: PYTHON=3.5.4
    language: generic
    sudo: true
  - os: osx
    env: PYTHON=3.6.5
    language: generic
    sudo: true
  - os: osx
    env: PYTHON=3.7.0
    language: generic
    sudo: true
install: ".travis/install.sh"
script: ".travis/run.sh"
after_success:
- codecov
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: Cq4Y2dwkNNE7hIZSEtmvNHI/2TZYzKpAJqbb6QPKG0hilx3PGetbs7fWy+ru6gRVW7A494Yk/4+ZO/9A92Pn0QHbbWtJZuU61pC2zxtkH2VKAzMVFly4gkL7L5Q9B8drAoer1usI4OtlN7eyqegTGAT8NEbhaynsJweEDZbWCWoXdQkl4tX6pYyDX/6HAWkfsQLaLPczLACyKYl812qAt7u6fFD+hcjdVrs/LfM9Cdt1gW3t9cVNm/Lqmla+I5OYjRRgbHm4XgsTrhNR0IoAxbktcxSwemnjTzwTsn7VQ9y4t8NlBRB5LUfw/0ihehKl7O4QS2c1G1uLhKHZZSfU8Di/qGGSvj/QBFvyZPDA8a/fmMBrNIHwy4k46l1ZfdDnX65oDbncHuXcFOVlTx85C5Zpy86tQDVktXf3kDlzsUtLgKtAY5dvLMDAwTvkX5M05DMwC51A+b2wsM1zs14CkeTFjHfsBIhDek91YfUEx6dRmnhg1KXVA+q02DKNoI0D5sNkOcgBnVATQOo29zcRKnyit93LBG3EiQYiIhubtwMkveXlEE3Qd5bUSdVuTMObN2nhm1bmYGrJ68dR+zKbsBZ51fcar6YeecmLCF6epBcZI++3AEH5/gu4qXb7A2pbxtiARJtxliI83d6CwEycPWhpjQ4p5UnByMhvKnKv14w=

before_deploy:
  - "pip install --upgrade twine setuptools"
deploy:
  provider: pypi
  user: slarse
  password:
    secure: kJd7TqF/04ckEJ1NZo6rRh2UQnai3CCSaXUh1KevOYSw7nPDJ/S2Avggn25t0wz5LNo1e6j1ksgZhWt2lxnOFZJRJO74GJaFhvfLg033jXT7gL09nfj5tr2HhVM0XWbZDj5SO+aW9J7A+8pPV0Zx4OcjyVdE3lqBUNv2qi0bQZE9MjVPUAA75OLMvOdHu/Kc1B1M1kSm7UQrj61llwUrNNWVjl7EB2gd0b+V7qO3sdMhO9FOARCBmH7ocuPgN8J2QfKWRj/6gUQ8p83BzCx67JF3G1qys1EcQCN+WVevwhgqwmJCHtYKOBGl3VwH5seTIOQ/Pyqrd9Y/owV/E/O4N4dSWcHA+KVMGen8lAlis6Ohxv2JtEeYzMVnr1Y9VPWckhTf6lbzNVGV2A8YZtJuSL5xRCX13lrfpkqMS/jM7TYSoVDTbLFZT6LJYWCy8uKrXZpRcHrENtoXYmWGbNoTc56x7t4VDfHaH3gaL4OLywQYZBiPClBPrgn8fECwpZZhED7O1b/ozsp8A6w7/DcOPBRnxXSJxPK9vdhFWOtyVz1X/TRITNNlyfUC7osDtF4Eass3n6YeTIIxuW8ELeZ8/eiRgIxiiBIHwM5qV/EmWCGdZvrTKjNG0CrwsHA7+rLQ0GZV3COr6SphLrY0V6fFyMJXmyX0LgWG9RRdlotYEYE=
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_OS_NAME = "linux"
  distributions: "sdist bdist_wheel"
  skip_existing: true
